name: Build C++
run-name: ${{ github.actor }} testing C++ Build
on: [push]

jobs:
  Build-CPP:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init
        with:
          languages: "cpp"

      - name: Preparing Build
        run: cmake -B build CPP
        shell: bash

      - name: Build
        run: cmake --build build
        shell: bash
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze

      - name: Running Unit Tests
        run: cmake -E chdir build ctest
        shell: bash

