name: Test Env
on:
  workflow_dispatch:

env:
  VERSION: '0.13.0'

jobs:
 test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Print Version
        uses: ./actions/printAction
        with:
          greeting: "Ryan $VERSION"
